export const COLLECTIONS = {
  PATIENTS: process.env.NEXT_PUBLIC_MVP_PATIENTS_COLLECTION_ID!,
  APPOINTMENTS: process.env.NEXT_PUBLIC_MVP_APPOINTMENTS_COLLECTION_ID!,
  DIAGNOSES: process.env.NEXT_PUBLIC_MVP_DIAGNOSES_COLLECTION_ID!,
  INVOICES: process.env.NEXT_PUBLIC_MVP_INVOICES_COLLECTION_ID!,

  RECEPTIONISTS: process.env.NEXT_PUBLIC_MVP_RECEPTIONISTS_COLLECTION_ID!,
  DOCTORS: process.env.NEXT_PUBLIC_MVP_DOCTORS_COLLECTION_ID!,
  PHARMACISTS: process.env.NEXT_PUBLIC_MVP_PHARMACISTS_COLLECTION_ID!,
  LABTECHNICIANS: process.env.NEXT_PUBLIC_MVP_LABTECHNICIANS_COLLECTION_ID!,
};