export const COLLECTIONS = {
  PATIENTS: process.env.NEXT_PUBLIC_PATIENTS_COLLECTION_ID!,
  APPOINTMENTS: process.env.NEXT_PUBLIC_APPOINTMENTS_COLLECTION_ID!,
  DIAGNOSES: process.env.NEXT_PUBLIC_MVP_DIAGNOSES_COLLECTION_ID!,
  SERVICE_LIST: process.env.NEXT_PUBLIC_SERVICE_LIST_COLLECTION_ID!,
  PHARMACY_PRODUCTS: process.env.NEXT_PUBLIC_PHARMACY_PRODUCTS_COLLECTION_ID!,

  INVOICES: process.env.NEXT_PUBLIC_INVOICES_COLLECTION_ID!,
  INVOICE_ITEMS: process.env.NEXT_PUBLIC_INVOICE_ITEMS_COLLECTION_ID!,
  INVOICE_PAYMENTS: process.env.NEXT_PUBLIC_INVOICE_PAYMENTS_COLLECTION_ID!,
  INVOICE_AUDIT_LOGS: process.env.NEXT_PUBLIC_INVOICE_AUDIT_LOGS_COLLECTION_ID!,
  INVOICE_ATTACHMENTS: process.env.NEXT_PUBLIC_INVOICE_ATTACHMENTS_COLLECTION_ID!,
  SETTINGS: process.env.NEXT_PUBLIC_SETTINGS_COLLECTION_ID!,
  SEQUENCES: process.env.NEXT_PUBLIC_SEQUENCES_COLLECTION_ID!,

  PROVIDER_SCHEDULE: process.env.NEXT_PUBLIC_PROVIDER_SCHEDULE_COLLECTION_ID!,
  
  PRINT_TEMPLATES: process.env.NEXT_PUBLIC_PRINT_TEMPLATES_COLLECTION_ID!,

  RECEPTIONISTS: process.env.NEXT_PUBLIC_MVP_RECEPTIONISTS_COLLECTION_ID!,
  DOCTORS: process.env.NEXT_PUBLIC_DOCTORS_COLLECTION_ID!,
  PHARMACISTS: process.env.NEXT_PUBLIC_MVP_PHARMACISTS_COLLECTION_ID!,
  NURSES: process.env.NEXT_PUBLIC_NURSES_COLLECTION_ID!,
  
  LABTECHNICIANS: process.env.NEXT_PUBLIC_LABTECHNICIANS_COLLECTION_ID!,
  LABTESTCATALOG: process.env.NEXT_PUBLIC_LAB_TESTCATALOG_COLLECTION_ID!,
  LABRESULTS: process.env.NEXT_PUBLIC_LAB_RESULTS_COLLECTION_ID!,
  LABRESULTDETAILS: process.env.NEXT_PUBLIC_LAB_RESULTDETAILS_COLLECTION_ID!,
  LABREPORTS: process.env.NEXT_PUBLIC_LAB_REPORTS_COLLECTION_ID!,
};