export const COLLECTIONS = {
  PATIENTS: process.env.NEXT_PUBLIC_PATIENTS_COLLECTION_ID!,
  APPOINTMENTS: process.env.NEXT_PUBLIC_MVP_APPOINTMENTS_COLLECTION_ID!,
  DIAGNOSES: process.env.NEXT_PUBLIC_MVP_DIAGNOSES_COLLECTION_ID!,
  INVOICES: process.env.NEXT_PUBLIC_MVP_INVOICES_COLLECTION_ID!,
  RECEPTIONISTS: process.env.NEXT_PUBLIC_MVP_RECEPTIONISTS_COLLECTION_ID!,
  DOCTORS: process.env.NEXT_PUBLIC_MVP_DOCTORS_COLLECTION_ID!,
  PHARMACISTS: process.env.NEXT_PUBLIC_MVP_PHARMACISTS_COLLECTION_ID!,
  
  LABTECHNICIANS: process.env.NEXT_PUBLIC_LABTECHNICIANS_COLLECTION_ID!,
  LABTESTCATALOG: process.env.NEXT_PUBLIC_LAB_TESTCATALOG_COLLECTION_ID!,
  LABRESULTS: process.env.NEXT_PUBLIC_LAB_RESULTS_COLLECTION_ID!,
  LABRESULTDETAILS: process.env.NEXT_PUBLIC_LAB_RESULTDETAILS_COLLECTION_ID!,
  LABREPORTS: process.env.NEXT_PUBLIC_LAB_REPORTS_COLLECTION_ID!,
};